### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by DavidsonGomes**
Evolution API version 2.0.0 update

Progress:

- [x] Cleaning up the general API code
- [x] Removing excessive verbose logs
- [x] Removal of authentication with jwt
- [x] Mongo db removal with mongoose
- [x] Standardized all request bodies to use camelCase
- [x] Changed the .env file configuration, removed the yml version and added .env to the repository root
- [x] Removed the mobile type connection with Baileys
- [x] Postgres implementation via prism orm
- [x] MySQL implementation via prism orm
- [x] Simplified payloads and endpoints
- [x] Typebot review and improvements
- [x] Chatwoot review and improvements
- [x] Adjust search for chats, messages and contacts
- [x] Review integration with official WhatsApp API
- [x] Review official WhatsApp API with Chatwoot and Typebot
- [x] Review endpoints that do not work correctly
- [x] Implement file storage with minio and s3

Work In Progress...

### CODE REVIEW

**Comment by DavidsonGomes** [comment]
Waiting for tests and validations

**Comment by MattCarneiro** [comment]
For some reason, you removed Instagram and Facebook integration from the progress checklist /sadface

**Comment by DavidsonGomes** [comment]
> For some reason, you removed Instagram and Facebook integration from the progress checklist /sadface

This list is for the first version of 2.0, it will be released in the next

**Comment by francisbreit** [comment]
Sugestão para desativar chatbots acidentais em Grupos: Criação de uma variável para este fim>
Problema:  Esses dias estava testando eu a evo 2.0 alpha com typebot usando triggerType = “all”) e, acidentalmente esqueci de desativar e o bot funcionou em vários grupos. 
Solução: Seria interessante termos uma variável no typebot/create que pudesse desativar  (opcionalmente) o bot para grupos. Tipo: keepGroups (true ou false).

**Comment by raphaelandriott** [comment]
por favor continuem!!! vejo isso sendo um dos maiores potenciais de transformação para muitas empresas!

**Comment by dpaes** [comment]
3.1.0-homolog está linda a mudança no front do manager
Só falta colocar importação de imagens e stickers na prox atualização (ao sincronizar)

**Comment by dpaes** [comment]
sugestão pra v2 e proxima release do v1 (#892)

**Comment by jesus-chacon** [comment]
A good feature could be implement the [read flag to use it for custom integrations ](https://github.com/EvolutionAPI/evolution-api/issues/925)

**Pull request closed without merging**
